language: node_js
node_js:
  - "22"
  - "20"

branches:
  only:
    - main
    - master

cache:
  directories:
    - node_modules

install:
  - npm ci

script:
  - npm run lint
  - npm run build
  # Tạm thời bỏ npm test vì chưa có tests